"""
Django settings for citta project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

#os.environ['DJANGO_SETTINGS_MODULE'] = 'citta.settings'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jg%162)y=l4*0zmcy%lle_xi2a%n=*x%&u6+05l1x2ep9d)kfv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['appspot.com'] 
ALLOWED_HOSTS = []


# Application definition
#
INSTALLED_APPS = [
    'scheduler.apps.SchedulerConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'citta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'citta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
# [START db_setup]
import os
if os.getenv('SERVER_SOFTWARE', '').startswith('Google App Engine'):
    # Running on production App Engine, so use a Google Cloud SQL database.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '/cloudsql/cittademo-148708:citta-demo',
            'NAME': 'cittadb',
            'USER': 'root',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'cittadb',
            'USER': 'cittauser',
            'PASSWORD':'cittauser',
            'HOST': '173.194.109.72',
            'PORT': '3306',
        }
    }
# [END db_setup]
AUTHENTICATION_BACKENDS = [
	'allauth.account.auth_backends.AuthenticationBackend',
	'django.contrib.auth.backends.ModelBackend',
]


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Pacific'

USE_I18N = True

USE_L10N = True

USE_TZ = False

#LOCAL
#GOOGLE_OAUTH2_CLIENT_ID = '677760922985-61mffv28v8pgl6jtchatqofj7deh2egf.apps.googleusercontent.com' 

#CITTAi-148708
GOOGLE_OAUTH2_CLIENT_ID = '677760922985-r0d9ifiq2ab807seks7lcerlr3utltv1.apps.googleusercontent.com' 

#LOCAL
#GOOGLE_OAUTH2_CLIENT_SECRET = 'G1TR8yuEf-ZOldQPE95i7aaY'

#CITTA-148708
GOOGLE_OAUTH2_CLIENT_SECRET = 'vrsGSDp3gcBzV3Fa9i1X-6TD'

SOCIAL_AUTH_COMPLETE_URL_NAME = 'socialauth_complete'

SOCIAL_AUTH_ASSOCIATE_URL_NAME = 'socialauth_associate_complete'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

# SITE_ID: 1 for local, 2 for citta-148708.blogspot.com
SITE_ID = 2

#CITTA-148708
STATIC_ROOT = 'https://storage.googleapis.com/citta-bucket/static/'

#LOCAL
STATIC_URL ='/static/'
#STATIC_URL = '/static/'
LOGIN_URL = '/scheduler/login/'

LOGIN_REDIRECT_URL = '/scheduler/'
