# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[(b'HW', b'HW'), (b'Test', b'Test'), (b'Extracurricular', b'Extracurricular')], default=b'HW', max_length=20)),
                ('due_date', models.DateField()),
                ('total_time', models.IntegerField()),
                ('attention_span', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('break_time', models.IntegerField()),
                ('study_start', models.TimeField()),
                ('study_end', models.TimeField()),
                ('study_days', models.IntegerField(choices=[(0, b'Monday'), (1, b'Teusday'), (2, b'Wednesday'), (3, b'Thursday'), (4, b'Friday'), (5, b'Saturday'), (6, b'Sunday')])),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
