# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20160826_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='study_days',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='study_days',
            field=models.ManyToManyField(to='scheduler.Day'),
        ),
    ]
