# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20160826_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mock_date',
            field=models.DateField(default=datetime.date(2016, 9, 2)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mock_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
