runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.9"

builtins:
- django_wsgi: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?script\ \(dev\).tmpl$
