runtime: python27
vm: true
entrypoint: gunicorn -b :$PORT citta.wsgi
threadsafe: true
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?script\ \(dev\).tmpl$
